### ISSUE TITLE
relation to /difference with fitnotes?

### ISSUE THREAD

**Issue by Dieterbe** [armpatch/TrainingLog#35]
Hi, i see in your readme:

> UI Design based on FitNotes by James Gay.

your app looks very similar, almost identical. so could you clarify what is the difference between this app and fitnotes? Is it a fork? I was actually trying to find the source code for fitnotes but can't find it anywhere

**Comment by armpatch** [comment]
It's not a fork, I wrote all the code here myself and just used the fitnotes app as a design reference. I've used FitNotes for years as my own workout tracker, and I just wanted to see if I could recreate the app for practice. Fitnotes actually has many more features and is a better app overall.

**Comment by Dieterbe** [comment]
Thanks Aaron. cheers!
